name: Deploy on server
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test before deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
        continue-on-error: false

  deploy:
    name: Deploy branch main
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script: |
            su vladf
            cd /home/vladf/guichet-clone
            source venv/bin/activate
            git config --global user.email "${{ secrets.GIT_EMAIL }}"
            git config --global user.name "${{ secrets.GIT_USERNAME }}"
            git config --global --add safe.directory /home/vladf/guichet-clone
            git pull origin main
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn